services:
  - type: web
    name: hotel-reservation-app
    runtime: docker
    plan: free
    region: singapore
    autoDeployTrigger: commit
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: APP_NAME
        value: The Grand Lion Hotel
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        sync: false
      - key: APP_KEY
        sync: false
      - key: FORCE_HTTPS
        value: "true"
      - key: TRUSTED_PROXIES
        value: "*"
      - key: APP_TIMEZONE
        value: Asia/Manila
      - key: LOG_CHANNEL
        value: stderr
      - key: DB_CONNECTION
        value: mysql
      - key: DB_URL
        sync: false
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      - key: FILESYSTEM_DISK
        value: public
      - key: MAIL_MAILER
        value: log
      - key: QR_MERCHANT_NAME
        value: The Grand Lion Hotel
